version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/next/Dockerfile
      target: runner
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/app/node_modules
    networks:
      - app-network

  external:
    build:
      context: .
      dockerfile: ./docker/external/Dockerfile
    ports:
      - "5050:5050"
    restart: always
    volumes:
      - ./docker/external/templates:/etc/nginx/templates
      - ./src/external:/var/www
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
    networks:
      - app-network

volumes:
  node_modules:

networks:
  app-network:
    driver: bridge
